name: devper

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*
  - tests
scripts:
  prepare:
    run: |
      melos clean && \
      melos bootstrap
    description: |
      Install package after setup project
  analyze:
    run: |
      melos exec -c 1 --ignore="*example*" -- \
      flutter analyze --fatal-infos .
    description: |
      Analyze all code.

  build:web:pos:
    run: |
      melos exec -c 1 --scope pos -- \
      flutter build web --release && \
    description: |
      Build.
    
  deploy:web:devper:
    run: |
      melos exec -c 1 --scope pos -- \
      firebase deploy --only hosting:devper
    description: |
      Deploy.   

  deploy:web:pos:
    run: |
      melos exec -c 1 --scope pos -- \
      firebase deploy --only hosting:pos
    description: |
      Build and Deploy.          

  import_sorter:
    run: |
      melos exec -c 1 -- \
      flutter pub run import_sorter:main
    description: |
      Import Sorter.
  

