name: sm
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  common:
  design_system:
  um:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/images/logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: packages/common/assets/font/roboto_regular.ttf
        - asset: packages/common/assets/font/roboto_bold.ttf
          weight: 700
